### ISSUE TITLE
Failed to add account module, can't compile

### ISSUE THREAD

**Issue by peter-luo-git** [hexya-addons/account#11]
➜  demoaccount hexya updatedb -o
Please wait, Hexya is starting ...
# github.com/hexya-erp/pool/m
pool/m/company.go:58:17: undefined: AccountJournalSet
pool/m/company.go:64:24: undefined: AccountJournalSet
.....

Detailed info as below.

➜  demoaccount hexya generate .
filename: /Users/peterluo/Work/Hengping/Hexya/demoaccount/pool/go.mod
data:
// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

module github.com/hexya-erp/pool

Hexya Generate
	--------------
Modules paths:
 - github.com/hexya-addons/web
 - github.com/hexya-addons/account
1/5 - Loading program...Ok
2/5 - Generating symlinks...Ok
3/5 - Generating pool...Ok
4/5 - Checking the generated code...Ok
5/5 - Creating main.go in project...Ok
Pool generated successfully
➜  demoaccount hexya updatedb -o
Please wait, Hexya is starting ...
# github.com/hexya-erp/pool/m
pool/m/company.go:58:17: undefined: AccountJournalSet
pool/m/company.go:64:24: undefined: AccountJournalSet
pool/m/company.go:76:18: undefined: AccountChartTemplateSet
pool/m/company.go:82:25: undefined: AccountChartTemplateSet
pool/m/company.go:837:17: undefined: AccountJournalSet
pool/m/company.go:842:24: undefined: AccountJournalSet
pool/m/company.go:851:29: undefined: AccountJournalData
pool/m/company.go:868:18: undefined: AccountChartTemplateSet
pool/m/country_group.go:112:15: undefined: ProductPricelistSet
pool/m/country_group.go:118:22: undefined: ProductPricelistSet
pool/m/company.go:868:18: too many errors
➜  demoaccount cat go.mod
module github.com/peterluo/demoaccount

go 1.14

replace github.com/hexya-erp/pool v1.0.2 => /Users/peterluo/Work/Hengping/Hexya/demoaccount/pool

require (
	github.com/hexya-addons/account v0.0.41
	github.com/hexya-addons/web v0.1.1
	github.com/hexya-erp/hexya v0.1.1
	github.com/spf13/cobra v0.0.5
)
➜  demoaccount

**Comment by peter-luo-git** [comment]
closed

**Comment by jjjachyty** [comment]
@peter-luo-git  can you tell me,how to solve it？
