### ISSUE TITLE
Got error : cannot use field (type string) as type models.FieldName in argument to aml.Get

### ISSUE THREAD

**Issue by jay009id** [hexya-addons/account#13]
I'm trying to convert the account addons to the stable version of hexya. Unfortunately, I got error when perform `hexya updatedb -o`. I don't understand how to convert a string to model.FieldName type as Get parameter.  The error :

```
cannot use field (type string) as type models.FieldName in argument to aml.Get:
	string does not implement models.FieldName (missing JSON method)
```

The example code is something like this : 
https://github.com/hexya-addons/account/blob/0ac664f1144cfc7add8937de0269df2f4c7771f7/account_move.go#L1314

Is there any clue how to solve this? Thanks in advance.

**Comment by npiganeau** [comment]
Hi @jay009id ,

You should define the field as a FieldName above : 

For instance, use `field = q.accountMoveLine().AmountResidual()` instead of `field = "AmountResidual"`. This was changed for type safety.

**Comment by jay009id** [comment]
Hi @npiganeau , thanks for the guidance.

**Comment by jay009id** [comment]
Hi @npiganeau , thanks for the guidance.
