### ISSUE TITLE
Func models.ConvertToFieldNameSlice has been removed

### ISSUE THREAD

**Issue by jay009id** [hexya-addons/account#14]
I don't see any replacement for func `models.ConvertToFieldNameSlice` that used in line :

https://github.com/hexya-addons/account/blob/0ac664f1144cfc7add8937de0269df2f4c7771f7/partner.go#L675

Is there anything else that can be use to replace `models.ConvertToFieldNameSlice` ? Thanks in advance.

**Comment by npiganeau** [comment]
Did you try : 
```go
append(rs.Super().CommercialFields(), []models.FieldNamer{
  q.Partner().DebitLimit(), 
  q.Partner().PropertyAccountPayable(),
[...]
 })
```

Basically the idea is that you should never have to write a field as a string.

**Comment by jay009id** [comment]
Thanks, it work well
